services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - 5555:5432

  rails:
    build: ./
    command: /usr/bin/supervisord
    # ports:
      # - 3000:3000
      # - 7860:7860
    volumes:
      - .:/instant-messenger
    depends_on:
      - postgres
    env_file:
      - './docker-bin/env.sh'

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
      # - 443:443
    volumes:
      - ./docker-bin/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rails

volumes:
  postgres: